# Generated by Django 3.1.7 on 2021-02-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_auto_20210226_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
