# Generated by Django 3.1.7 on 2021-02-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_auto_20210226_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
